# Generated by Django 4.2.5 on 2026-08-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonCastRESTAPI', '0006_metric_type_and_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast168',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(db_index=True, max_length=32)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('issued_at', models.DateTimeField(db_index=True)),
                ('emission_factor_type', models.CharField(max_length=32)),
                ('value', models.FloatField()),
                ('metric_unit', models.CharField(default='gCO2eq/kWh', max_length=32)),
                ('source_type', models.CharField(default='model_forecast', max_length=32)),
                ('provider', models.CharField(default='carboncast', max_length=32)),
                ('forecast_run_id', models.CharField(db_index=True, max_length=64)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='emissionactual',
            new_name='CarbonCastR_region_772d82_idx',
            old_name='emission_region_metric_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='forecast96',
            new_name='CarbonCastR_region_b2c5e9_idx',
            old_name='forecast_region_metric_ts_idx',
        ),
        migrations.AddIndex(
            model_name='forecast168',
            index=models.Index(fields=['region_code', 'datetime'], name='CarbonCastR_region__6707cc_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast168',
            index=models.Index(fields=['region_code', 'issued_at'], name='CarbonCastR_region__b2b215_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast168',
            index=models.Index(fields=['forecast_run_id'], name='CarbonCastR_forecas_1a61eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forecast168',
            unique_together={('region_code', 'datetime', 'issued_at', 'source_type', 'emission_factor_type')},
        ),
    ]
