# Generated by Django 4.2.5 on 2026-08-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonCastRESTAPI', '0007_forecast168_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forecast168',
            unique_together={('region_code', 'datetime', 'source_type', 'emission_factor_type')},
        ),
    ]
