import os
import csv
import math
from pathlib import Path
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, permissions
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi
from ..consts import carbon_cast_version, authentication_classes, permission_classes
from ._base import safe_float, check_throttle_limit


class ForecastValidationApiView(APIView):
    """
    Returns actual vs. predicted validation/test data generated by the ML models
    from the CI_forecast_data directory for a given region and emission factor type.
    """
    authentication_classes = authentication_classes
    permission_classes = permission_classes

    @swagger_auto_schema(
        manual_parameters=[
            openapi.Parameter(
                'region',
                openapi.IN_QUERY,
                description="Region code parameter (e.g., 'AECI', 'CISO').",
                type=openapi.TYPE_STRING,
                required=True
            ),
            openapi.Parameter(
                'emissionType',
                openapi.IN_QUERY,
                description="Emission factor type ('direct' or 'lifecycle').",
                type=openapi.TYPE_STRING,
                default='direct'
            ),
            openapi.Parameter(
                'runIndex',
                openapi.IN_QUERY,
                description="Run index suffix (default '0').",
                type=openapi.TYPE_STRING,
                default='0'
            ),
        ],
        responses={
            200: 'HTTP 200 OK - Returns validation time-series data and summary metrics',
            400: 'HTTP 400 Bad Request - Missing or invalid parameters',
            404: 'HTTP 404 Not Found - No validation dataset found for requested region/type',
        }
    )
    def get(self, request, *args, **kwargs):
        if permissions.AllowAny not in permission_classes:
            user = request.user
            if not check_throttle_limit(user):
                return Response({
                    "status": "fail",
                    "message": "Throttle limit reached",
                    "carbon_cast_version": carbon_cast_version
                }, status=status.HTTP_429_TOO_MANY_REQUESTS, headers={'Retry-After': 86400})

        region = (
            request.query_params.get('region') or
            request.query_params.get('region_code') or
            request.query_params.get('regionCode') or
            ''
        ).strip().upper()

        if not region:
            return Response(
                {"error": "Missing required query parameter 'region'"},
                status=status.HTTP_400_BAD_REQUEST
            )

        emission_type = (
            request.query_params.get('emissionType') or
            request.query_params.get('emission_type') or
            request.query_params.get('cef_type') or
            'direct'
        ).strip().lower()

        if emission_type not in ('direct', 'lifecycle'):
            return Response(
                {"error": "Parameter 'emissionType' must be either 'direct' or 'lifecycle'"},
                status=status.HTTP_400_BAD_REQUEST
            )

        run_index = (
            request.query_params.get('runIndex') or
            request.query_params.get('run_index') or
            '0'
        ).strip()

        # Locate CI_forecast_data directory across potential deployment layouts:
        # 1. settings.BASE_DIR / "CI_forecast_data" (Render production Root Directory & local CarbonCastAPI)
        # 2. 5 levels up (Monorepo root for local development)
        # 3. CI_FORECAST_DATA_DIR environment variable
        from django.conf import settings
        candidate_dirs = [
            settings.BASE_DIR / "CI_forecast_data",
            Path(__file__).resolve().parent.parent.parent.parent.parent / "CI_forecast_data",
            Path(os.environ.get("CI_FORECAST_DATA_DIR", "")) if os.environ.get("CI_FORECAST_DATA_DIR") else None,
        ]

        file_path = None
        for cand in candidate_dirs:
            if cand and cand.exists():
                fp = cand / region / f"{region}_{emission_type}_168hr_CI_forecasts_{run_index}.csv"
                if fp.is_file():
                    file_path = fp
                    break

        if not file_path or not file_path.is_file():
            return Response(
                {
                    "error": f"No validation dataset found for region '{region}', emission type '{emission_type}', run '{run_index}'",
                    "data": [],
                    "carbon_cast_version": carbon_cast_version
                },
                status=status.HTTP_404_NOT_FOUND
            )

        rows = []
        errors = []
        sq_errors = []
        pct_errors = []

        try:
            with open(file_path, "r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    dt = row.get("datetime") or ""
                    actual = safe_float(row.get("carbon_intensity_actual"))
                    predicted = safe_float(row.get("avg_carbon_intensity_forecast"))

                    rows.append({
                        "datetime": dt,
                        "actual": actual,
                        "predicted": predicted
                    })

                    if actual is not None and predicted is not None:
                        err = abs(actual - predicted)
                        errors.append(err)
                        sq_errors.append(err ** 2)
                        if actual > 0:
                            pct_errors.append((err / actual) * 100.0)

            mae = (sum(errors) / len(errors)) if errors else None
            rmse = math.sqrt(sum(sq_errors) / len(sq_errors)) if sq_errors else None
            mape = (sum(pct_errors) / len(pct_errors)) if pct_errors else None

            return Response({
                "region": region,
                "emission_type": emission_type,
                "run_index": run_index,
                "count": len(rows),
                "metrics": {
                    "mae": round(mae, 2) if mae is not None else None,
                    "rmse": round(rmse, 2) if rmse is not None else None,
                    "mape": round(mape, 2) if mape is not None else None
                },
                "data": rows,
                "carbon_cast_version": carbon_cast_version
            }, status=status.HTTP_200_OK)

        except Exception as exc:
            return Response(
                {
                    "error": f"Error reading validation file: {str(exc)}",
                    "data": [],
                    "carbon_cast_version": carbon_cast_version
                },
                status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )
